import type { SxProps, Theme } from "@mui/material/styles";

export const editorSx: SxProps<Theme> = {
  "& .ProseMirror-yjs-cursor": {
    position: "relative",
    marginLeft: "-1px",
    marginRight: "-1px",
    borderLeft: "2px solid",
    borderRight: "none",
    wordBreak: "normal",
    pointerEvents: "none",
    "& > div": {
      position: "absolute",
      top: "-1.4em",
      left: "-1px",
      fontSize: "0.65rem",
      fontWeight: 600,
      lineHeight: "normal",
      padding: "1px 5px",
      borderRadius: "3px 3px 3px 0",
      color: "#fff",
      whiteSpace: "nowrap",
      pointerEvents: "none",
    },
  },
  "& .ProseMirror": {
    outline: "none",
    minHeight: "60vh",
    fontSize: "1.02rem",
    lineHeight: 1.78,
    color: "text.primary",
    caretColor: "primary.main",
    "& .is-empty::before": {
      content: "attr(data-placeholder)",
      float: "left",
      color: "text.disabled",
      pointerEvents: "none",
      height: 0,
      fontStyle: "italic",
    },
    "& h1": {
      fontSize: "1.75rem",
      fontWeight: 800,
      letterSpacing: "-0.03em",
      lineHeight: 1.2,
      mt: "1.6em",
      mb: "0.3em",
    },
    "& h2": {
      fontSize: "1.38rem",
      fontWeight: 700,
      letterSpacing: "-0.02em",
      lineHeight: 1.3,
      mt: "1.4em",
      mb: "0.3em",
    },
    "& h3": {
      fontSize: "1.12rem",
      fontWeight: 700,
      letterSpacing: "-0.01em",
      mt: "1.15em",
      mb: "0.25em",
    },
    "& blockquote": {
      borderLeft: "3px solid",
      borderColor: "primary.main",
      pl: 2.5,
      color: "text.secondary",
      my: 2,
      ml: 0,
      fontStyle: "italic",
      opacity: 0.85,
    },
    "& ul, & ol": { pl: 3 },
    "& li + li": { mt: 0.375 },
    "& p": { my: 0.75 },
    "& p:first-of-type": { mt: 0 },
    "& img.lumen-img": {
      maxWidth: "100%",
      height: "auto",
      borderRadius: "6px",
      display: "block",
      my: 1.5,
    },
    "& .lumen-comment": {
      backgroundColor: "rgba(228, 184, 74, 0.22)",
      borderBottom: "1.5px solid rgba(184, 128, 74, 0.55)",
      borderRadius: "2px",
      cursor: "pointer",
      padding: "0 1px",
      transition: "background-color 0.15s",
      "&:hover": { backgroundColor: "rgba(228, 184, 74, 0.38)" },
    },
    "& .tableWrapper": {
      overflowX: "auto",
      my: 1.5,
    },
    "& .tableWrapper table": {
      width: "100%",
      borderCollapse: "collapse",
      tableLayout: "fixed",
      "& td, & th": {
        border: "1px solid",
        borderColor: "divider",
        padding: "8px 12px",
        verticalAlign: "top",
        position: "relative",
        "& > *": { mt: 0, mb: 0 },
      },
      "& th": {
        backgroundColor: "action.hover",
        fontWeight: 700,
        textAlign: "left",
      },
      "& .selectedCell": {
        backgroundColor: "rgba(139,155,110,0.12)",
      },
      "& .column-resize-handle": {
        position: "absolute",
        right: "-2px",
        top: 0,
        bottom: 0,
        width: "4px",
        backgroundColor: "primary.main",
        opacity: 0.25,
        pointerEvents: "none",
      },
    },
    "&.resize-cursor": { cursor: "col-resize" },
  },
};
